[package]
name = "fzscenario"
version.workspace = true
edition = "2024"

[lib]
name = "fzscenario"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml.workspace = true
blake3 = "1.5.4"
clap = { version = "4.5.16", features = ["derive"] }
globset = "0.4.15"
rand_chacha = "0.3.1"
rand_core = { version = "0.6.4", features = ["getrandom"] }
time = { version = "0.3.36", features = ["formatting", "macros", "serde", "parsing"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
ureq = "2.10.1"
uuid = { version = "1.10.0", features = ["serde", "v4"] }
walkdir = "2.5.0"
zip = { version = "2.2.0", default-features = false, features = ["deflate"] }

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"

[lints.rust]
warnings = "deny"
